name: erp-congnghegiaoduc

on:
push:
    branches:
      - master
      - fastrackids
 pull_request:
    branches:
      - master
      - fastrackids
    
jobs:
  congnghegiaoduc_production:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Pull
      run: sudo git pull origin master
      working-directory: /var/www/html/erp
    - name: Complete
      run: sudo npm run production
      working-directory: /var/www/html/erp
      
  congnghegiaoduc_fastrackids:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/fastrackids'
    steps:
    - name: Pull
      run: sudo git pull origin fastrackids
      working-directory: /var/www/html/fastrackids
    - name: Complete
      run: sudo npm run production
      working-directory: /var/www/html/fastrackids
