name: erp-congnghegiaoduc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  congnghegiaoduc_production:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Pull
      run: sudo git pull origin master
      working-directory: /var/www/html/erp
    - name: Complete
      run: sudo npm run production
      working-directory: /var/www/html/erp
